### PR TITLE
move c declarations into pxd file

### PR DESCRIPTION
**Pull request by Mng-dev-ai**

### CODE REVIEW

**Comment by Mng-dev-ai** [comment]
@siddhantgoel  I think there's a problem with type name in `def __init__(self, str name, object target):` so the compiler complains with `Cannot convert Unicode string to 'str' implicitly. This is not portable and requires explicit encoding.`
Maybe it should be `bytes` not `str`

**Comment by siddhantgoel** [comment]
Hey, these values are being passed directly from the outside `Parser` class. That data normally comes from the parameter names the user is expecting, which are normally strings, so this sounds like a breaking change.

I'm not sure if I understood how you ran into the compiler error, because the `.c` file seems to have updated contents. :thinking:

**Comment by siddhantgoel** [comment]
Bump :)

**Comment by Mng-dev-ai** [comment]
Sorry for the delay, I was very busy.
 I will check it today or tomorrow.

**Comment by Mng-dev-ai** [comment]
@siddhantgoel The problem was that I forgot to add to `# cython: language_level=3` in the `pxd` file.

**Comment by siddhantgoel** [comment]
@Mng-dev-ai there might be something else going on too. The tests are failing with an error `_parser.data_received failed with delimiting multipart stream into parts`.

**Comment by siddhantgoel** [comment]
@Mng-dev-ai would you like to pick this up again?

**Pull request closed without merging**
