### PR TITLE
Use async/await for data_received flow

### PR DESCRIPTION
**Pull request by alvin-trusttoken**

### CODE REVIEW

**Comment by siddhantgoel** [comment]
Hey, quick comment here. The parser is purely CPU based and there are no IO waits or anything in there (at least for now). Do you think adding async/await here would still be helpful?

**Comment by alvin-trusttoken** [comment]
Hi, meant to make a PR for my forked branch, sorry about that. 

Anyway, since we are discussing, I will describe my use case. I am building an async API server (let’s say ServerA) using Quart (basically an async port of Flask) with a file upload endpoint. I would like this API to upload the file chunks to another service (say ServerB) in parallel using another API as they come in, rather than wait for the entire file to be received from the client.

The reason I am using this library is that Quart (nor Flask) doesn’t seem to have built-in support for streaming parsed files from multipart/form-data requests. In my case, the API requests to ServerB need to be async, as I am trying to keep non-blocking I/O for as much things as possible.

I set up a custom target that looks something like
```
class CustomTarget(BaseTarget):
    is_async = True

    async def on_data_received(self, data):
        await <call async function that sends file chunk Server B via API call>
```

```
target = CustomTarget()
parser.register('file', target)

async for chunk in request.body:
    await parser.data_received(chunk)
```

I tried to figure out a way to do this without modifying the library, but you cannot really call async code from synchronous code (which is what `on_data_received` is). I could try to spin up a thread or async task but I would lose ordering guarantees and such.

I took a stab at the minimal changes I would need, and I got my use case to completely work! That said there are obvious downsides as well, and my change probably is not ideal. Folks using this with normal sync code (without event loop) won’t be able to use this. I don’t love how the async/await statements also “spread” upwards through the code. Maybe there is a better implementation or way to do this better, which will probably be a larger refactor. I'm not the biggest expert on Python asyncio.

That said, given that this library is focused on streaming, I also wouldn’t be surprised if async use cases make a lot of sense.

Thanks for making this library, it's been very useful! If you think adding async might be useful/feasible, I'm happy to help work on this.

**Comment by siddhantgoel** [comment]
For the use case you described, supporting async/await would definitely be useful. This could actually also help with #3 .

We **could** think about marking `Target.data_received` as async. And then it would depend on the sub-targets whether they just `return` or also contain an `await` in their implementations of `on_data_received`. The current targets included in `targets.py` would probably stay unaffected, but for instance for a target like the one you're probably using, there would be an `await` in there somewhere.

The only open question is if making this change would break existing code. I mean a little bit, of course, but other than replacing a few `def`s with `async def`s, not sure if the breakage would be **that** big.

**Comment by siddhantgoel** [comment]
More thoughts: I'm somehow not too inclined on replacing sync with async. One option would be to define an additional `data_received`-like method which returns something that's `await`able so you could call `await` on it. This way we could keep both the sync and async interfaces.

This would require having async-enabled `Target`s, and probably also an additional function in the `Part` class. But sounds kinda doable.

**Comment by alvin-trusttoken** [comment]
i think that sounds better than replacing the sync methods. it'd be great if you can pull it off. let me know how it goes or if you have something you'd like me to test out

**Pull request closed without merging**
